### ISSUE TITLE
not working orange pi lite

### ISSUE THREAD

**Issue by serhatkimya** [Eunanibus/MMM-Globe#4]
hi, i worked it at windows but at my orange pi lite, it is not working, there is no problem seems. thanks

**Comment by serhatkimya** [comment]
is there anyone help me? i read some forums and somebody says this isssue about OPENGL. is it possible? or is there anyone like me?

**Comment by ac1dphr3aq** [comment]
you are alone :[

**Comment by Eunanibus** [comment]
Hi Serhatkimya,

As you are experiencing issues that other users have had (and resolved) - I'd encourage you to take a look at the [forum posting](https://forum.magicmirror.builders/topic/2553/mmm-globe) and subsequent user questions that have been answered to see if this solves your question.

A lighter version of this module for Pi's is currently being developed.
