### ISSUE TITLE
MMM-Globe is not loading

### ISSUE THREAD

**Issue by aro28** [Eunanibus/MMM-Globe#7]
![capture](https://user-images.githubusercontent.com/25077676/41026955-ac25909e-6997-11e8-9d63-2513e15c97d8.PNG)
Hi,
MMM-Globe is not loading /showing .
What's wrong? Does it work now?

**Comment by aro28** [comment]
Fixed.

**Comment by amshoo** [comment]
@aro28  how do you fixed it

**Comment by aro28** [comment]
hi @amshoo 
I just activated OpenGL driver on Pi3.

**Comment by amshoo** [comment]
@aro28 mine is not showing but i think maybe is from my network.

**Comment by SaschaSp** [comment]
@aro28 
have you a manual or HowTo to activate OpenGL driver PI3?

**Comment by BrianHepler** [comment]
Here are instructions on how to enable the OpenGL driver: https://github.com/michmich/magicmirror/wiki/configuring-the-raspberry-pi#enable-the-open-gl-driver-to-decrease-electrons-cpu-usage

**Comment by Eunanibus** [comment]
The documentation found at the original forum post indicates that OpenGL drivers must be activated prior to running. We also do not recommend running the application on a Pi3 as it tends to be too underpowered to run this application.
