### ISSUE TITLE
Blank module

### ISSUE THREAD

**Issue by ghost** [Eunanibus/MMM-Globe#8]
Hi,

I`m trying to run your module on a Tinker Board, the module loads but does not show anything. Are there any specific requirements for the module? Magic mirror says that there are no error with the module, added the default config for the module in the config file.

Any help is appreciated.

**Comment by BrianHepler** [comment]
I never did get around to completing that module. I'm not sure it ever worked. 

 

I really should delete it to keep people from trying it. :)

 

There is another module out there that does display a globe and it might run on a Tinker board. I was developing this one for a Fitlet.  

 

You should probably try this module. I think it's complete: https://github.com/Eunanibus/MMM-Globe

**Comment by ghost** [comment]
I do not understand what module you refer to. You sent me the exact same link to this one.

**Comment by ghost** [comment]
Solved the issue. I installed electron beta that support Open GL. Now it works.

**Comment by Eunanibus** [comment]
Glad this was solved. I'll probably add this to the readme as it seems to be a frequent troubleshooting step - a quick google would have taken you to [this thread](https://forum.magicmirror.builders/topic/2553/mmm-globe) where it's mentioned a few times!
